<!DOCTYPE html>
<html>
    <head>
        <?php wp_head();?>
    </head>
    <body id="ve-editor-template" class="ve-editor-view">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
		    var js, fjs = d.getElementsByTagName(s)[0];
		    if (d.getElementById(id)) return;
		    js = d.createElement(s); js.id = id;
		    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
		    fjs.parentNode.insertBefore(js, fjs);
	    }(document, 'script', 'facebook-jssdk'));</script>
        <?php the_post();?>
        <div class="ve-the-editor">
            <ve-editor>
                <?php the_content();?>
            </ve-editor>
        </div>
        <?php wp_footer();?>

    </body>
</html>