<?php
/**
 * @var VE_Editor $editor
 * @var VE_View_Manager $this
 */

?><div id="ve-panel" class="<?php echo $editor->getPostType();?>">

    <div class="panel-wrapper">

        <div class="ve-form-wrapper" id="ve-element-form-wrapper">
            <div class="form-header">
                <h3 class="form-title"></h3>
                <a href="#" class="close-element-form"><i class="form-close-icon"></i></a>
            </div>
            <form id="ve-element-form" class="ve-form pure-form">
                <div class="form-content">

                </div>
                <div class="form-control">
                    <input type="submit" value="Apply" class="save"/>
                </div>
            </form>
            <div class="loading-indicator">
                <div class="loading-inner">
                    <div class="spinner"></div>
                </div>
            </div>
        </div>

        <div class="ve-form-wrapper" id="ve-element-form-wrapper-2">
            <div class="form-header">
                <h3 class="form-title"></h3>
                <a href="#" class="close-element-form"><i class="form-close-icon"></i></a>
            </div>
            <form id="ve-element-form-2" class="ve-form pure-form">
                <div class="form-content">

                </div>
                <div class="form-control">
                    <input type="submit" value="Apply" class="save"/>
                </div>
            </form>

        </div>



        <div class="panel-items">
            <div class="panel-item">
                <?php
                //

                ?>

            </div>
            <div id="panel-item-1" class="panel-item element-list">
                <?php $this->render('panel/element-list');?>
            </div>
        </div>
    </div>
        <div class="ve-col-xs-12 promo-area" style="position: fixed; right: 0; bottom: 5px;">
	        <div id="tutorial">
		        <a target="_blank" href="https://www.youtube.com/playlist?list=PL6rw2AEN42ErEJxrni93gb4solJXW74mI"><i class="fa fa-book"></i> Tutorial</a>
	        </div>
	        <div id="support">
		        <a target="_blank" href="http://allinonewpbuilder.com/contact"><i class="fa fa-support"></i> Support</a>
	        </div>
	        <div class="ve-col-xs-6" id="promo-link">
				<a target="_blank" href="http://allinonewpbuilder.com/?src=infreeedit"><i class="fa fa-star"></i> Get Ultimate version</a>
	        </div>

	        <?php
	        $promoContent = wp_remote_get('http://allinonewpbuilder.com/services/promo.txt');

	        if (is_array($promoContent))
	        {
		        echo '<div id="promo-content" style="display:none;">';

		        echo $promoContent['body'];
		        echo '</div>';
	        }
	        ?>



    </div>
</div>
<a class="closePopup close-element-form" href="#"></a>

<script>
	(function(jQuery){
		jQuery(function(){
			var promoLink = jQuery('#promo-link a');
			var promoContent = JSON.parse(jQuery('#promo-content').text());

			setInterval(function(){
				//get a random object from the promo content and add to the link
				var randomLink = promoContent[Math.floor(Math.random() * (promoContent.length -
					1))];

				promoLink.attr('href', randomLink.url);
				promoLink.html('<i class="fa fa-star"></i> ' + randomLink.text);

			}, 5000);





		});



	})(jQuery);

</script>